### ISSUE TITLE
网站打不开了

### ISSUE THREAD

**Issue by liuyongfei1** [superRaytin/redux-saga-in-chinese#31]
hi：
http://leonshi.com/redux-saga-in-chinese/docs/introduction/BeginnerTutorial.html
该网址已经无法打开了

**Comment by zjafei** [comment]
嗯 打不开了

**Comment by farzer** [comment]
+1

**Comment by superRaytin** [comment]
国内注册的域名要实名认证了。。预计 5 月底前才可恢复访问

**Comment by superRaytin** [comment]
已恢复
