### ISSUE TITLE
Beginner Tutorial 部分代码与官方文档不一致

### ISSUE THREAD

**Issue by cloudychen** [superRaytin/redux-saga-in-chinese#33]
官方文档中的示例代码
// ...
import { createStore, applyMiddleware } from 'redux'
import createSagaMiddleware from 'redux-saga'

// ...
import { helloSaga } from './sagas'

**const sagaMiddleware = createSagaMiddleware()**
const store = createStore(
  reducer,
  **applyMiddleware(sagaMiddleware)**
)
**sagaMiddleware.run(helloSaga)**

const action = type => store.dispatch({type})

// rest unchanged

翻译中的示例代码
// ...
import { createStore, applyMiddleware } from 'redux'
import createSagaMiddleware from 'redux-saga'

//...
import { helloSaga } from './sagas'

const store = createStore(
  reducer,
  **applyMiddleware(createSagaMiddleware(helloSaga))**
)

// rest unchanged

使用翻译中的示例代码运行，并不能接入saga，作为新手，回去看原文才明白哪里错了，还望更新。

**Comment by edwardwang0302** [comment]
昨天晚上我也是刚刚看了这个发现有问题，就顺便把有问题的翻译部分已经修正了，现在就等owner确认然后合入了
