### ISSUE TITLE
为什么中文网的和英文的差这么多

### ISSUE THREAD

**Issue by Nealyang** [superRaytin/redux-saga-in-chinese#41]
跟着中文网的代码写出来都跑不起来。。。

**Comment by charlie-cao** [comment]
过时了吧

**Comment by bravelincy** [comment]
对，连sagas.js里面export语句都不见了。

**Comment by TANSHUAI1001** [comment]
我也遇到问题了，跑去英文文档看下代码才能跑起来！
英文是将两个generator用all连起来，然后使用sagaMiddleware.run(rootSaga)
`export default function* rootSaga() {
    yield all([
      helloSaga(),
      watchIncrementAsync()
    ])
  }`
还有render函数Counter写得并不完整，虽然熟悉react的基本都能知道意思。

**Comment by cike8899** [comment]
已经有一年没更新了，大家有时间更新下吧！

**Comment by superRaytin** [comment]
抱歉，由于工作繁忙，文档落后很多。

文档同步至官方最新版本（v1.0.0-beta）的工作现已启动，欢迎认领！#46
