### ISSUE TITLE
高级-同时执行多个任务，应当为yield all([]), 缺少了all()函数调用

### ISSUE THREAD

**Issue by MeetzhDing** [superRaytin/redux-saga-in-chinese#67]
如题所示，在 https://redux-saga-in-chinese.js.org/docs/advanced/RunningTasksInParallel.html 中出现了这个问题，虽然此github源中的文档内容和英文原版没有出入，都是用的yield all([]), 但是在html版本的文档中并没有得到同步。

中文文档： https://redux-saga-in-chinese.js.org/docs/advanced/RunningTasksInParallel.html
此github源： https://github.com/superRaytin/redux-saga-in-chinese/tree/master/docs/advanced/RunningTasksInParallel.md

**Comment by vincentdd** [comment]
2019年10月，中文文档还是没有和MD同步

**Comment by hahaliangchen** [comment]
2020年6月24 依然没有同步还是错误的示范，我幸好上网查了查我用源码进行推导，发现也没啥特殊的啊，而且没执行功能
